name: Toronto Events Scraper

on:
  schedule:
    - cron: '0 7 * * *'  # Run daily at 7:00 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape-and-classify:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install puppeteer @supabase/supabase-js axios
      
      - name: Run scraper
        run: node server/src/scraper/scraper.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}